from __future__ import annotations

"""MotifGate: PWM-aware residual model for short-window TFBS prediction."""

__version__ = "1.0.0"

from .constants import (B2I, BACKGROUND_LIMIT, BACKGROUND_STRIDE, BASES, BATCH_SIZE, CGR_BITS, COMP, DEVICE, DROPOUT, D_MODEL, EPOCHS, FIXED_LEN, JASPAR_PWM_DIR, LABEL_SMOOTHING, LR, LR_MIN_FACTOR, NEG_CANDIDATE_TRIES, NEG_CAP_Q, NEG_GC_TOL_FRAC, NEG_PER_POS, NUM_EXPERTS, N_HEADS, PATIENCE, RC_AUGMENTATION, RESIDUAL_GATE_INIT, SEED, SITES_DIR, TEST_FRAC, TRAIN_FRAC, TRANSFAC_DIR, USE_SE_BLOCK, VAL_FRAC, WARMUP_EPOCHS_FRAC, WEIGHT_DECAY)
from .utils import (base_id, basic_scalar_features, canonical_seq, center_crop, count_parameters, count_trainable_parameters, encode_onehot, ensure_dir, estimate_base_probs, fcgr_features, gc_count, kmer_hash_features, parse_k_list_arg, pearson_corr, pwm_information_content, rankdata_average_ties, revcomp_seq, reverse_complement_pwm, safe_auc_ap, safe_name, safe_sigmoid_np, sample_random_seq, seq_to_idx, set_seed, spearman_rho, split_counts, stable_int, write_csv, write_json)
from .pwm_io import (JasparPWMIndex, MotifRecord, PWMIndex, TransfacIndex, best_alignment_score, compute_raw_prior_scores, extract_fixed_len_windows, load_background_sequences_from_dir, load_fasta_sequences, parse_sites_file)
from .data import (CapEstimator, HardNegativeSampler, FeatureNormalizer, LabeledExample, PoolItem, PositiveExample, RawPositiveExample, SplitBundle, TFBSDataset, TrainOnlyNegativeSampler, _assignment_objective, _assignment_state_from_map, _balanced_partition_exact, _balanced_partition_randomized, _is_valid_assignment, _local_improve_assignment, _target_counts, audit_split_integrity, balanced_partition_entities_by_sites, build_conflict_free_matched_subset_across_k, collate_batch, compute_feature_stats, crop_raw_example_to_fixed_len, crop_split_bundle_to_fixed_len, deduplicate_examples_global, deduplicate_raw_examples_global, examples_to_manifest_rows, export_split_leak_audit, group_value, load_positive_examples, load_raw_positive_examples_min_len, make_binary_split, make_feature_matrix, make_split_inventory_rows, make_weighted_sampler, split_group_heldout, split_motif_heldout_in_group, split_site_level_seen_motifs)
from .model import (AttentivePool, CleanTFBSHybrid, ExactPWMConv, LightMoE, PWMConvExactModel, PWMConvResidualHybrid, SqueezeExcitation, build_model, make_cosine_warmup_scheduler, reverse_complement_onehot_batch, reverse_complement_onehot_torch, seq_pwm_match_loss)
from .train import (binary_nll_from_probs, bootstrap_delta_ap, brier_score_binary, ece_binary, evaluate, evaluate_at_threshold, find_tau_for_target_fdr, fit_temperature_binary, make_datasets_and_stats, train_model)
from .interpret import (build_analysis_batch, export_calibration, export_ig_and_consistency, export_predictions_csv, export_pwm_reconstruction, integrated_gradients_single, predict_sequences, project_pwm_to_seq_matrix, select_test_indices_by_motif)
from .exports import (build_summary_row, export_architecture_summary, export_baseline_consistency_and_decomposition, export_worst_k_detailed, history_complete_header, history_rows_with_meta, make_per_motif_test_metrics, prior_baseline_rows_for_split, summary_header, write_global_history_exports, write_k_comparison_exports, write_k_matched_exports)
from .experiment import (run_single_experiment)
from .cli import (build_arg_parser, main)

__all__ = [
    'AttentivePool',
    'B2I',
    'BACKGROUND_LIMIT',
    'BACKGROUND_STRIDE',
    'BASES',
    'BATCH_SIZE',
    'CGR_BITS',
    'COMP',
    'CapEstimator',
    'CleanTFBSHybrid',
    'DEVICE',
    'DROPOUT',
    'D_MODEL',
    'EPOCHS',
    'ExactPWMConv',
    'FIXED_LEN',
    'FeatureNormalizer',
    'JASPAR_PWM_DIR',
    'JasparPWMIndex',
    'LABEL_SMOOTHING',
    'LR',
    'LR_MIN_FACTOR',
    'LabeledExample',
    'LightMoE',
    'MotifRecord',
    'NEG_CANDIDATE_TRIES',
    'NEG_CAP_Q',
    'NEG_GC_TOL_FRAC',
    'NEG_PER_POS',
    'NUM_EXPERTS',
    'N_HEADS',
    'PATIENCE',
    'PWMConvExactModel',
    'PWMConvResidualHybrid',
    'PWMIndex',
    'PoolItem',
    'PositiveExample',
    'RC_AUGMENTATION',
    'RESIDUAL_GATE_INIT',
    'RawPositiveExample',
    'SEED',
    'SITES_DIR',
    'SplitBundle',
    'SqueezeExcitation',
    'TEST_FRAC',
    'TFBSDataset',
    'TRAIN_FRAC',
    'TRANSFAC_DIR',
    'HardNegativeSampler',
    'TrainOnlyNegativeSampler',
    'TransfacIndex',
    'USE_SE_BLOCK',
    'VAL_FRAC',
    'WARMUP_EPOCHS_FRAC',
    'WEIGHT_DECAY',
    '_assignment_objective',
    '_assignment_state_from_map',
    '_balanced_partition_exact',
    '_balanced_partition_randomized',
    '_is_valid_assignment',
    '_local_improve_assignment',
    '_target_counts',
    'audit_split_integrity',
    'balanced_partition_entities_by_sites',
    'base_id',
    'basic_scalar_features',
    'best_alignment_score',
    'binary_nll_from_probs',
    'bootstrap_delta_ap',
    'brier_score_binary',
    'build_analysis_batch',
    'build_arg_parser',
    'build_conflict_free_matched_subset_across_k',
    'build_model',
    'build_summary_row',
    'canonical_seq',
    'center_crop',
    'collate_batch',
    'compute_feature_stats',
    'compute_raw_prior_scores',
    'count_parameters',
    'count_trainable_parameters',
    'crop_raw_example_to_fixed_len',
    'crop_split_bundle_to_fixed_len',
    'deduplicate_examples_global',
    'deduplicate_raw_examples_global',
    'ece_binary',
    'encode_onehot',
    'ensure_dir',
    'estimate_base_probs',
    'evaluate',
    'evaluate_at_threshold',
    'examples_to_manifest_rows',
    'export_architecture_summary',
    'export_baseline_consistency_and_decomposition',
    'export_calibration',
    'export_ig_and_consistency',
    'export_predictions_csv',
    'export_pwm_reconstruction',
    'export_split_leak_audit',
    'export_worst_k_detailed',
    'extract_fixed_len_windows',
    'fcgr_features',
    'find_tau_for_target_fdr',
    'fit_temperature_binary',
    'gc_count',
    'group_value',
    'history_complete_header',
    'history_rows_with_meta',
    'integrated_gradients_single',
    'kmer_hash_features',
    'load_background_sequences_from_dir',
    'load_fasta_sequences',
    'load_positive_examples',
    'load_raw_positive_examples_min_len',
    'main',
    'make_binary_split',
    'make_cosine_warmup_scheduler',
    'make_datasets_and_stats',
    'make_feature_matrix',
    'make_per_motif_test_metrics',
    'make_split_inventory_rows',
    'make_weighted_sampler',
    'parse_k_list_arg',
    'parse_sites_file',
    'pearson_corr',
    'predict_sequences',
    'prior_baseline_rows_for_split',
    'project_pwm_to_seq_matrix',
    'pwm_information_content',
    'rankdata_average_ties',
    'revcomp_seq',
    'reverse_complement_onehot_batch',
    'reverse_complement_onehot_torch',
    'reverse_complement_pwm',
    'run_single_experiment',
    'safe_auc_ap',
    'safe_name',
    'safe_sigmoid_np',
    'sample_random_seq',
    'select_test_indices_by_motif',
    'seq_pwm_match_loss',
    'seq_to_idx',
    'set_seed',
    'spearman_rho',
    'split_counts',
    'split_group_heldout',
    'split_motif_heldout_in_group',
    'split_site_level_seen_motifs',
    'stable_int',
    'summary_header',
    'train_model',
    'write_csv',
    'write_global_history_exports',
    'write_json',
    'write_k_comparison_exports',
    'write_k_matched_exports',
]
